### ISSUE TITLE
Wrong worker status

### ISSUE THREAD

**Issue by Zuko** [ylecuyer/puma-status#9] opened 2020-06-19 07:13 UTC
Hi

`puma-monitor` shows all workers as **killed** but they are working.

![azpHEcH](https://user-images.githubusercontent.com/521035/85104635-33b26300-b209-11ea-8285-ca519c04c8ae.gif)

Status was displayed properly for couple of hours.

Ruby: 2.5.7p206
Puma 4.3.5

**Comment by ylecuyer** [comment] 2020-12-06 20:11
Hello,

Could you tell me which operating system your are using (and the version) and which version of top you have (`top -v`)
I checked the code and the process is marked as killed if the pid isn't found in top or if the CPU and memory metrics are equal to 0 (https://github.com/ylecuyer/puma-status/blob/7dfb34afebbc0b0462f9b63a7ea307a1991559fc/lib/core.rb#L56). It seems to be the case in your screencast here because the worker is marked as killed but as soon as you have some CPU info it is marked as alive. I think top isn't giving the info of the used memory for those process leading to this error.

Regards

**Comment by kshnurov** [comment] 2021-01-28 16:25
Got the same problem. @ylecuyer my `top` shows RES in human-readable format (e.g. `988.6m`), that's the reason.

**Comment by ylecuyer** [comment] 2021-01-28 16:28
thanks for the exta info @kshnurov

Could you report the `top -v` here, do you know if you have a special config for top or if your distro has one (would be nice to have the distro info too).
With these info I may be able to reproduce

**Comment by kshnurov** [comment] 2021-01-28 16:44
@ylecuyer nothing special, old Debian 9.3. I guess it's been the default for quite a while to auto-choose the suffix depending on the value. There seems to be no command-line option to change that.
```
procps-ng 3.3.12
Usage:
  top -hv | -bcHiOSs -d secs -n max -u|U user -p pid(s) -o field -w [cols]
```

**Comment by Zuko** [comment] 2021-01-28 17:17
Sorry for late answer.

```
procps-ng 3.3.15
Usage:
  top -hv | -bcEHiOSs1 -d secs -n max -u|U user -p pid(s) -o field -w [cols]
```

Debian 10.

```
locale
LANG=pl_PL.UTF-8
LANGUAGE=
LC_CTYPE="pl_PL.UTF-8"
LC_NUMERIC="pl_PL.UTF-8"
LC_TIME="pl_PL.UTF-8"
LC_COLLATE="pl_PL.UTF-8"
LC_MONETARY="pl_PL.UTF-8"
LC_MESSAGES="pl_PL.UTF-8"
LC_PAPER="pl_PL.UTF-8"
LC_NAME="pl_PL.UTF-8"
LC_ADDRESS="pl_PL.UTF-8"
LC_TELEPHONE="pl_PL.UTF-8"
LC_MEASUREMENT="pl_PL.UTF-8"
LC_IDENTIFICATION="pl_PL.UTF-8"
LC_ALL=
```

**Comment by ylecuyer** [comment] 2021-01-28 20:43
Thanks for your help I was able to reproduce and I'll make a fix

**Comment by ylecuyer** [comment] 2021-01-28 22:37
I have release version 1.2 which should fix the issue.

Could you try and reopen if it is not the case?

**Closed by ylecuyer** 2021-01-28 22:37 UTC

**Comment by kshnurov** [comment] 2021-02-25 12:54
@ylecuyer thank you for the fix!
I've switched to jemalloc the same day and my workers never went over 1GB since then, so I can't reproduce it anymore :)
